### ISSUE TITLE
Road map to v0.0.1

### ISSUE THREAD

**Issue by green-coder** [green-coder/girouette#32]
Tasks not required for the v0.0.1 release (they can be done later):
- [x] Achieve 100%-ish compatibility with Tailwind v2.0.2 (issue #21)
- [x] Improve utility functions to make it easy to create own grammar rules (issue #34) 
- [x] ~Improve class names gathering from source code (issue #28)~ will be done in a separate library
- [x] Pre-release clean up, source code design review, documentation
- [x] Release and deploy on Clojars

Tasks not required for the v0.0.1 release (they can be done later):
- Demo: run Girouette in frontend land, regenerate and set CSS between reloads (issue #26)
- Implement the `@apply` equivalent, to combine class names together (issue #35)
- Leverage Girouette's approach to incorporate grammar for animation (issue #31)
- Make Girouette production ready, consider CSS minifying scenarios
